const Discord = require('discord.js')
const config = require('./config')

const PinoRouter = require('./lib/PinoRouter')
const PinoCommandFilter = require('./lib/PinoCommandFilter')
const PinoRegexFilter = require('./lib/PinoRegexFilter')
const ImagesController = require('./lib/ImagesController')
const BastonController = require('./lib/BastonController')
const DefinitionController = require('./lib/DefinitionController')
const ReactionController = require('./lib/ReactionController')
const CoolTextController = require('./lib/CoolTextController')
const PinoSchedule = require('./lib/PinoSchedule')

const PinoLogger = require('./lib/PinoLogger')

const client = new Discord.Client()

client.on('ready', () => {
  console.log('I am ready!')
  client.user.setActivity('Yuri scientific videos, for science.', {type: 'WATCHING'})
  PinoLogger.init(client, config.logServer, config.logChannel, config.enableChannelLog)
  new PinoSchedule(client)
})

let router = new PinoRouter(client)
let baston = new BastonController()
let images = new ImagesController()
let define = new DefinitionController(client)
let reaction = new ReactionController()
let cooltext = new CoolTextController()

router.when(new PinoCommandFilter('ok', 'cordialement, okay'), images.okHandler)
router.when(new PinoCommandFilter('flip_table', 'FUCK THAT SHIT'), images.flipTableHandler)
router.when(new PinoCommandFilter('vivement', 'hu hu hu, I really hope that tomorrow will come quickly.', '[url]'), images.vivementHandler.bind(images))
router.when(new PinoCommandFilter('baka', 'It\'s not that I like you or anything, b-b-baka!'), images.bakaHandler)
router.when(new PinoCommandFilter('police', 'That. Is. Not. Legal.'), images.callingThePoliceHandler)
router.when(new PinoCommandFilter('pic', 'Random pic from danbooru.', '[...tags]'), images.danbooruHandler)
router.when(new PinoCommandFilter('zpic', 'Random pic from zero chan (experimental).', '[...query]'), images.zeroChanHandler.bind(images))
router.when(new PinoCommandFilter('baston', 'FAITO~~', '[target]'), baston.bastonHandler.bind(baston))
router.when(new PinoCommandFilter('cast', 'Aren\'t you a wizzard my friend?', '[target] spell'), baston.castHandler.bind(baston))
router.when(new PinoCommandFilter('pram', 'PRAM'), images.pramHandler)
router.when(new PinoCommandFilter('define', 'Define some word', 'word'), define.urbanHandler.bind(define))
router.when(new PinoCommandFilter('d4rk', 'Display your pseudo but d4rk3r.', '[pseudo]'), cooltext.darkPseudoHandler)
router.when(new PinoCommandFilter('figlet', 'Figlet like text generator', 'text'), cooltext.figletHandler)
router.when(new PinoCommandFilter('salt', 'Salt', '@Someone'), images.saltHandler.bind(images))
router.when(new PinoCommandFilter('?', 'Display help.'), PinoCommandFilter.helpHandler)
router.when(new PinoRegexFilter(/(nep\s*){2}/gi), reaction.nepNepHandler)
router.when(new PinoRegexFilter(/was deleted$/gi), reaction.deleteHandler)
router.when(new PinoRegexFilter(/^deux$/gi), reaction.deuxHandler)

client.login(config.apiToken)
